### ISSUE TITLE
Identify Milestone 2 PBI's

### ISSUE THREAD

**Issue by Gard-en** [GPF104/GPF104_Game#42]

**Comment by Gard-en** [comment]
- [ ] Assets, animated first, UI second, environment last.
- [ ] Enemy details
- [ ] Refine, redefine mechanics (incorporate playtest feedback)
- [ ] Level decals, particles, extra juice
